name: Publish Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    uses: amattas/aviato/.github/workflows/reusable-docker-ghcr.yml@main
    with:
      context: "."
      dockerfile: "Dockerfile"
      platforms: "linux/amd64"
      scan-image: true
