# aviato:managed profile=aviato-library version=0 hash=88c462d522b02c68f10f3db39b32f900cf191826a1f8bc39da36c3a0fb5d436f inputs=76bd944abbcf93c5fc7686f5fdcf3b001c230442c29d97d4a07c86f5d0cc7232
name: Aviato Drift Detection
'on':
  schedule:
    - cron: 17 6 * * 1
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  drift:
    uses: ./.github/workflows/reusable-consumer-automation.yml
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      aviato-ref: '0'
      local-install: true
    secrets:
      settings-token: ${{ secrets.AVIATO_SETTINGS_TOKEN }}
